basePath: /v1
definitions:
  models.Task:
    properties:
      class:
        description: Class
        type: string
      completed:
        type: boolean
      completed_at:
        type: string
      content:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      created_by_login:
        description: Meta
        type: string
      due_date:
        type: string
      members:
        description: Students
        items:
          type: string
        type: array
      promotion:
        description: Promotion
        type: integer
      region:
        type: string
      semester:
        type: string
      short_id:
        description: Meta
        type: string
      subject:
        type: string
      title:
        description: Body
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
      updated_by_login:
        type: string
      visibility:
        type: string
    type: object
host: https://api.epitaf.fr
info:
  contact:
    email: contact@epitaf.fr
    name: Aurèle Oulès
    url: https://www.aureleoules.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Epitaf API v1 Docs
  version: "1.0"
paths:
  /classes:
    get:
      description: Get list of all registered classes
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Server error
      summary: Get classes
      tags:
      - classes
  /tasks:
    get:
      description: Get tasks
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error" "Server error
      summary: Get tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error
      summary: Create task
      tags:
      - tasks
  /tasks/{short_id}:
    delete:
      description: Delete a specific task
      parameters:
      - description: short_id
        in: path
        name: short_id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error
      summary: Delete task
      tags:
      - tasks
    get:
      description: Get a specific task
      parameters:
      - description: short_id
        in: path
        name: short_id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error" "Server error
      summary: Get task
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Edit a specific task
      parameters:
      - description: short_id
        in: path
        name: short_id
        required: true
        type: string
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error
      summary: Update task
      tags:
      - tasks
  /tasks/{short_id}/complete:
    delete:
      description: Mark a specific task as uncompleted
      parameters:
      - description: short_id
        in: path
        name: short_id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error
      summary: Uncomplete task
      tags:
      - tasks
    post:
      description: Mark a specific task as completed
      parameters:
      - description: short_id
        in: path
        name: short_id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error
      summary: Complete task
      tags:
      - tasks
  /users/authenticate:
    post:
      description: Build Microsoft oauth url
      parameters:
      - description: redirect_uri
        in: body
        name: redirect_uri
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
        "406":
          description: Not acceptable
      summary: Authenticate URL
      tags:
      - users
  /users/callback:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT
      parameters:
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      - description: redirect_uri
        in: body
        name: redirect_uri
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "406":
          description: Not acceptable
        "500":
          description: Server error
      summary: OAuth Callback
      tags:
      - users
swagger: "2.0"
