name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Go tests
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: docker build . -f ./docker/Dockerfile.test -t aureleoules/epitaf:$(date +%s)