name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Go tests
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: docker build . -f ./docker/Dockerfile.test -t aureleoules/epitaf:$(date +%s)
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        SECRET: ${{ secrets.SECRET }}
        CRI_USERNAME: ${{ secrets.CRI_USERNAME }}
        CRI_PASSWORD: ${{ secrets.CRI_PASSWORD }}
        CHRONOS_TOKEN: ${{ secrets.CHRONOS_TOKEN }}
        DEV: true
        TZ: Europe/Paris  